server:
    port: 8080
    servlet:
        context-path: /aieducboot
spring:
    devtools:
        enabled: true
    http:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
    mvc:
        view:
            prefix: /WEB-INF/views/
            subffix: .jsp       

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/db_ai_educ?useSSL=false&characterEncoding=utf8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 10
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    servlet:
        multipart:
            max-file-size: 5MB

mybatis:
    type-aliases-package: com.aieduc.entity
    mapper-locations: classpath:mapper/*.xml
logging:
    config: classpath:log4j2.yml
    level:
         com.aieduc.dao: info
site:
    files:
         uploadpath: E:/upload